# Import necessary modules
# Load the box and coin scenarios generated by 01_generate_scenarios.py.
# Define a function to simulate a fixed number of draws.
# - For each draw, randomly choose a box and then a coin based on the scenario.
# - Record results for whether the coin is gold or silver and the box chosen.
# Save simulation results to a CSV file in the outputs/ folder.